version: '3.8'
services:
  slate_api_scripts:
    container_name: slate_api_scripts
    image: slate_api_scripts:local
    command: "cp -f /resources/docker/conf/slate.conf /slate/slate.conf"
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile
      target: local-stage
    environment:
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SLATE_API_ENDPOINT: ${SLATE_API_ENDPOINT}
      SLATE_API_PORT: ${SLATE_API_PORT}
      SLATE_API_TOKEN: ${SLATE_API_TOKEN}
    volumes:
      - ./scripts:/slate/scripts
      - ./resources:/resources
