version: '3.8'
services:
  slate_api_scripts:
    container_name: slate_api_scripts
    image: slate_api_scripts:local
    command: "/resources/docker/scripts/init/api-scripts.sh"
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile
      target: local-stage
    environment:
      DYNAMO_AWS_SECRET_ACCESS_KEY: ${DYNAMO_AWS_SECRET_ACCESS_KEY}
      DYNAMO_AWS_ACCESS_KEY_ID: ${DYNAMO_AWS_ACCESS_KEY_ID}
      DYNAMO_AWS_DEFAULT_REGION: ${DYNAMO_AWS_DEFAULT_REGION}
      DYNAMO_AWS_ENDPOINT: ${DYNAMO_AWS_ENDPOINT}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_CHECKMK_BUCKET: ${AWS_CHECKMK_BUCKET}
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      SLATE_API_CONF: ${SLATE_API_CONF}
      SLATE_API_ENDPOINT: ${SLATE_API_ENDPOINT}
      SLATE_API_PORT: ${SLATE_API_PORT}
      SLATE_API_TOKEN: ${SLATE_API_TOKEN}
    tty: true
    volumes:
      - ./resources/docker/conf:/slate/conf
      - ./scripts:/slate/scripts
      - ./resources:/resources
